name: Activity Box

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    name: 🚀 Update activity box
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: ⚡️ Update Recent Activity
        uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: borjapazr
          GIST_ID: a55c854aa947b6a08a298f7694a0f01f
